/**
 * searchEngine.js — Scored semantic search engine for Cheatsheet Piscinas.
 *
 * Supports ES/CA, accented/unaccented, professional/colloquial,
 * curated intent boosting, disambiguation rules, and alias fallback.
 */

// ── Text normalization ────────────────────────────────────────────────────────

export function normalizeSearchText(value) {
  return String(value ?? '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .replace(/[^\p{Letter}\p{Number}\s]/gu, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// ── Deep flattening ───────────────────────────────────────────────────────────

export function flattenForSearch(value) {
  if (value == null) return '';
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) return value.map(flattenForSearch).join(' ');
  if (typeof value === 'object') return Object.values(value).map(flattenForSearch).join(' ');
  return String(value);
}

// ── Build searchable text from all ficha fields ───────────────────────────────

export function buildSearchableText(f) {
  return flattenForSearch([
    f.id,
    f.titulo,
    f.categoria,
    f.subcategoria,
    f.prioridad,
    f.palabras_clave,
    f.sinonimos_busqueda,
    f.sinonimos,
    f.situacion_visible,
    f.riesgo_inmediato,
    f.descartar_urgente,
    f.comprobaciones_rapidas,
    f.parametros,
    f.decision_sop,
    f.protocolo,
    f.calculo_rapido,
    f.causa_raiz_probable,
    f.solucion_paliativa,
    f.solucion_definitiva,
    f.por_que_recurre,
    f.construccion,
    f.que_no_hacer,
    f.cuando_cerrar_bano,
    f.cuando_parar_equipo,
    f.cuando_derivar,
    f.cliente,
    f.parte,
    f.fuentes,
    f.nota_precision,
    // legacy fields
    f.sintomas,
    f.acciones,
    f.problema_explicado,
    f.causas,
    f.interpretacion_resultados,
    f.calculo_producto,
    f.productos,
    f.arbol_relacionado,
    f.checklist,
    f.seguimiento,
  ]);
}

// ── Index builders ────────────────────────────────────────────────────────────

export function buildIntentIndex(vocabulary) {
  return (vocabulary.curated_intents ?? []).map(intent => ({
    ...intent,
    searchable: normalizeSearchText(flattenForSearch([
      intent.label,
      intent.intent_id,
      intent.query_examples_es,
      intent.query_examples_ca,
      intent.colloquial_expressions,
      intent.professional_terms,
    ])),
  }));
}

export function buildAliasIndex(vocabulary) {
  return (vocabulary.autogenerated_ficha_aliases ?? []).map(alias => ({
    ...alias,
    searchable: normalizeSearchText(flattenForSearch([
      alias.label,
      alias.primary_ficha_id,
      alias.primary_ficha_title,
      alias.query_examples_es,
      alias.query_examples_ca,
      alias.professional_terms,
    ])),
  }));
}

export function buildSearchContext(vocabulary) {
  return {
    intentIndex: buildIntentIndex(vocabulary),
    aliasIndex: buildAliasIndex(vocabulary),
    categoryVocabulary: vocabulary.category_vocabulary ?? {},
    disambiguationRules: vocabulary.disambiguation_rules ?? [],
  };
}

// ── Scoring helpers ───────────────────────────────────────────────────────────

function scoreIntentForFicha(ficha, query, terms, intentIndex) {
  let score = 0;
  const reasons = [];

  for (const intent of intentIndex) {
    const s = intent.searchable;
    const phraseMatch   = s.includes(query);
    const allTermsMatch = terms.length > 1 && terms.every(t => s.includes(t));
    const someTermMatch = terms.some(t => t.length >= 3 && s.includes(t));

    if (!phraseMatch && !allTermsMatch && !someTermMatch) continue;

    const base = intent.priority_boost ?? 100;

    if (ficha.id === intent.primary_ficha_id) {
      if (phraseMatch)        score += base + 80;
      else if (allTermsMatch) score += base + 40;
      else                    score += Math.round(base * 0.5);
      reasons.push(`curated-primary:${intent.intent_id}`);
    }

    if (intent.secondary_ficha_ids?.includes(ficha.id)) {
      if (phraseMatch)        score += Math.round(base * 0.6);
      else if (allTermsMatch) score += Math.round(base * 0.4);
      else                    score += Math.round(base * 0.25);
      reasons.push(`curated-secondary:${intent.intent_id}`);
    }
  }

  return { score, reasons };
}

function scoreAliasForFicha(ficha, query, terms, aliasIndex) {
  let score = 0;
  const reasons = [];

  for (const alias of aliasIndex) {
    if (alias.primary_ficha_id !== ficha.id) continue;
    const s = alias.searchable;
    const phraseMatch   = s.includes(query);
    const allTermsMatch = terms.length > 1 && terms.every(t => s.includes(t));
    const someTermMatch = terms.some(t => t.length >= 3 && s.includes(t));

    if (phraseMatch)        { score += 50; reasons.push('alias-phrase'); }
    else if (allTermsMatch) { score += 25; reasons.push('alias-all-terms'); }
    else if (someTermMatch) { score += 10; reasons.push('alias-some'); }
  }

  return { score, reasons };
}

function scoreCategoryVocabulary(ficha, terms, categoryVocabulary) {
  let score = 0;
  const reasons = [];
  const fichaText = normalizeSearchText(flattenForSearch([ficha.categoria, ficha.subcategoria]));

  for (const [cat, vocabObj] of Object.entries(categoryVocabulary)) {
    const catNorm = normalizeSearchText(cat);
    if (!fichaText.includes(catNorm)) continue;
    const allTerms = normalizeSearchText(flattenForSearch(Object.values(vocabObj)));
    for (const term of terms) {
      if (term.length >= 3 && allTerms.includes(term)) {
        score += 10;
        reasons.push(`cat-vocab:${cat}:${term}`);
      }
    }
  }

  return { score, reasons };
}

export function scoreDisambiguation(ficha, query, terms, rules) {
  let score = 0;
  const reasons = [];

  for (const rule of rules) {
    const ifTerms = (rule.if_query_contains ?? []).map(normalizeSearchText);
    const anyMatch = ifTerms.some(t => query.includes(t));
    if (!anyMatch) continue;

    const unlessTerms = (rule.unless_also_contains ?? []).map(normalizeSearchText);
    if (unlessTerms.length > 0 && unlessTerms.some(t => query.includes(t))) continue;

    if (rule.prefer && ficha.id === rule.prefer) {
      score += 200;
      reasons.push(`disambig-prefer:${rule.prefer}`);
    }
    if (rule.avoid && ficha.id === rule.avoid) {
      score -= 300;
      reasons.push(`disambig-avoid:${rule.avoid}`);
    }
    if (rule.also_consider?.includes(ficha.id)) {
      score += 60;
      reasons.push(`disambig-also:${ficha.id}`);
    }
  }

  return { score, reasons };
}

// ── Main scoring function ─────────────────────────────────────────────────────

export function scoreFicha(ficha, rawQuery, context) {
  const query = normalizeSearchText(rawQuery);
  if (!query) return { score: 1, reasons: ['empty-query'] };

  const terms = query.split(' ').filter(t => t.length >= 2);

  const title    = normalizeSearchText(ficha.titulo ?? '');
  const idNorm   = normalizeSearchText(ficha.id ?? '');
  const keywords = normalizeSearchText(flattenForSearch([ficha.palabras_clave, ficha.sinonimos_busqueda, ficha.sinonimos]));
  const body     = normalizeSearchText(buildSearchableText(ficha));

  let score = 0;
  const reasons = [];

  // Phrase matches
  if (title.includes(query))    { score += 120; reasons.push('title-phrase'); }
  if (idNorm.includes(query.replace(/\s+/g, '_'))) { score += 100; reasons.push('id-phrase'); }
  if (keywords.includes(query)) { score += 90;  reasons.push('kw-phrase'); }
  if (body.includes(query))     { score += 45;  reasons.push('body-phrase'); }

  // Per-term scoring
  for (const term of terms) {
    if (title.includes(term))    { score += 25; reasons.push(`title:${term}`); }
    if (keywords.includes(term)) { score += 18; reasons.push(`kw:${term}`); }
    if (body.includes(term))     { score += 5;  reasons.push(`body:${term}`); }
  }

  // Curated intent boost
  const intent = scoreIntentForFicha(ficha, query, terms, context.intentIndex);
  score += intent.score;
  reasons.push(...intent.reasons);

  // Alias fallback
  const alias = scoreAliasForFicha(ficha, query, terms, context.aliasIndex);
  score += alias.score;
  reasons.push(...alias.reasons);

  // Category vocabulary boost
  const cat = scoreCategoryVocabulary(ficha, terms, context.categoryVocabulary);
  score += cat.score;
  reasons.push(...cat.reasons);

  // Disambiguation rules
  const disamb = scoreDisambiguation(ficha, query, terms, context.disambiguationRules);
  score += disamb.score;
  reasons.push(...disamb.reasons);

  return { score, reasons };
}

// ── Main search function ──────────────────────────────────────────────────────

export function searchFichas(allFichas, rawQuery, context, { categoria = null } = {}) {
  if (!rawQuery || !rawQuery.trim()) {
    let list = allFichas;
    if (categoria) list = list.filter(f => f.categoria === categoria);
    return list.map(f => ({ ficha: f, score: 1, reasons: [] }));
  }

  let list = allFichas;
  if (categoria) list = list.filter(f => f.categoria === categoria);

  const scored = list
    .map(f => ({ ficha: f, ...scoreFicha(f, rawQuery, context) }))
    .filter(r => r.score > 0)
    .sort((a, b) => b.score - a.score);

  return scored;
}
